"""empty message

Revision ID: 4f3d2e410643
Revises: 
Create Date: 2026-05-10 18:08:07.299906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3d2e410643'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('match_type', sa.Enum('SINGLE', 'TOURNAMENT', name='eventmatchtype'), nullable=False),
    sa.Column('use_application', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('team_formation', sa.Enum('DRAFT', 'BALANCE', 'MANUAL', name='teamformation'), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'REGISTRATION', 'IDLE', 'FORMATION', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='eventstatus'), nullable=False),
    sa.Column('allow_multiple_drafts', sa.Boolean(), nullable=False),
    sa.Column('rating_set_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_custom_field_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WAITLIST', name='applicationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'member_id', name='uq_application_event_member')
    )
    op.create_table('application_time_settings_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('bracket_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('draft_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'BALANCE_REQUESTED', 'BALANCE_SELECTED', 'COMPLETED', name='draftstatus'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizer_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('required_integration_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'provider_id', name='uq_required_integration_event_provider')
    )
    op.create_table('selected_game_role_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_role_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('override_max_count', sa.Integer(), nullable=True),
    sa.Column('override_min_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_role_id', 'event_id', name='uq_selected_game_role_event')
    )
    op.create_table('application_integration_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.Column('user_provider_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'user_provider_id', name='uq_app_integration_app_provider')
    )
    op.create_table('event_player_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('custom_id', sa.Uuid(), nullable=True),
    sa.Column('is_draft_pinned', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('REGISTERED', 'SELECTED', 'PLAYING', 'COMPLETED', 'BENCHED', name='eventplayerstatus'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_table.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'member_id', name='uq_event_player_member')
    )
    op.create_table('filled_application_field_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('custom_field_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['application_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['custom_field_id'], ['application_custom_field_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_field_id', 'application_id', name='uq_filled_app_field_custom_app')
    )
    op.create_table('stage_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('SINGLE_MATCH', 'SINGLE_ELIMINATION', 'DOUBLE_ELIMINATION', 'ROUND_ROBIN', 'SWISS', name='stageformat'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bracket_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bracket_id', 'stage_index', name='uq_stage_bracket_index')
    )
    op.create_table('team_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_table.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bracket_placement_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bracket_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bracket_id', 'placement', name='uq_bracket_placement_placement'),
    sa.UniqueConstraint('bracket_id', 'team_id', name='uq_bracket_placement_team')
    )
    op.create_table('drafted_player_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('event_player_id', sa.Uuid(), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['draft_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_player_id'], ['event_player_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'event_player_id', name='uq_drafted_player_draft_player')
    )
    op.create_table('player_role_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('game_role_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('event_player_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_player_id'], ['event_player_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['game_role_id'], ['selected_game_role_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_role_id', 'event_player_id', name='uq_player_role_game_role_player')
    )
    op.create_table('round_robin_settings_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('meetings_per_pair', sa.Integer(), nullable=False),
    sa.Column('score_system', sa.String(), nullable=False),
    sa.Column('score_per_win', sa.Integer(), nullable=True),
    sa.Column('score_per_draw', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id')
    )
    op.create_table('stage_group_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('advance_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swiss_settings_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stage_id', sa.Uuid(), nullable=False),
    sa.Column('score_per_win', sa.Integer(), nullable=False),
    sa.Column('score_per_draw', sa.Integer(), nullable=False),
    sa.Column('score_per_bye', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stage_id'], ['stage_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stage_id')
    )
    op.create_table('team_player_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('game_role_id', sa.Uuid(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_role_id'], ['selected_game_role_table.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team_table.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'member_id', name='uq_team_player_team_member')
    )
    op.create_table('match_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('match_index', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('bracket_position', sa.Enum('UPPER', 'LOWER', name='bracketposition'), nullable=True),
    sa.Column('result_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['stage_group_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'match_index', name='uq_match_group_index')
    )
    op.create_table('match_slot_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('match_id', sa.Uuid(), nullable=False),
    sa.Column('slot_num', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.Enum('WINNER_OF', 'LOSER_OF', 'GROUP_PLACEMENT', 'MANUAL', 'AUTO', name='matchslotsourcetype'), nullable=False),
    sa.Column('source_match_id', sa.Uuid(), nullable=True),
    sa.Column('source_group_id', sa.Uuid(), nullable=True),
    sa.Column('group_placement', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_group_id'], ['stage_group_table.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_match_id'], ['match_table.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'slot_num', name='uq_match_slot_match_num')
    )
    op.create_table('match_score_table',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slot_id', sa.Uuid(), nullable=False),
    sa.Column('team_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['match_slot_table.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_score_table')
    op.drop_table('match_slot_table')
    op.drop_table('match_table')
    op.drop_table('team_player_table')
    op.drop_table('swiss_settings_table')
    op.drop_table('stage_group_table')
    op.drop_table('round_robin_settings_table')
    op.drop_table('player_role_table')
    op.drop_table('drafted_player_table')
    op.drop_table('bracket_placement_table')
    op.drop_table('team_table')
    op.drop_table('stage_table')
    op.drop_table('filled_application_field_table')
    op.drop_table('event_player_table')
    op.drop_table('application_integration_table')
    op.drop_table('selected_game_role_table')
    op.drop_table('required_integration_table')
    op.drop_table('organizer_table')
    op.drop_table('draft_table')
    op.drop_table('bracket_table')
    op.drop_table('application_time_settings_table')
    op.drop_table('application_table')
    op.drop_table('application_custom_field_table')
    op.drop_table('event_table')
    # ### end Alembic commands ###
