from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.application_time_settings import ApplicationTimeSettings, ApplicationTimeSettingsCreate, ApplicationTimeSettingsUpdate


class ApplicationTimeSettingsRepositoryProtocol(Protocol):
    async def get_by_event_id(self, event_id: UUID, load_event: bool) -> ApplicationTimeSettings | None: ...

    async def delete_by_event_id(self, event_id: UUID) -> None: ...

    async def get(self, field_id: UUID) -> ApplicationTimeSettings | None: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[ApplicationTimeSettings]: ...

    async def create(self, dto: ApplicationTimeSettingsCreate) -> ApplicationTimeSettings: ...

    async def update(self, dto: ApplicationTimeSettingsUpdate) -> ApplicationTimeSettings: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
