from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.application_custom_field import ApplicationCustomField, ApplicationCustomFieldCreate, ApplicationCustomFieldUpdate


class ApplicationCustomFieldRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_event: bool) -> ApplicationCustomField | None: ...

    async def list_by_event(self, event_id: UUID) -> Sequence[ApplicationCustomField]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[ApplicationCustomField]: ...

    async def create(self, dto: ApplicationCustomFieldCreate) -> ApplicationCustomField: ...

    async def update(self, dto: ApplicationCustomFieldUpdate) -> ApplicationCustomField: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
