from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.application_integration import ApplicationIntegration, ApplicationIntegrationCreate


class ApplicationIntegrationRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_application: bool = False) -> ApplicationIntegration | None: ...

    async def list_by_application(self, application_id: UUID) -> Sequence[ApplicationIntegration]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[ApplicationIntegration]: ...

    async def create(self, dto: ApplicationIntegrationCreate) -> ApplicationIntegration: ...

    async def update(self, dto: ApplicationIntegrationCreate) -> ApplicationIntegration: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
