from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.application import Application, ApplicationCreate, ApplicationUpdate, ApplicationStatus


class ApplicationRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_filled_fields: bool = False, load_integrations: bool = False,
                  load_event_player: bool = False) -> Application | None: ...

    async def get_by_event_and_member(self, event_id: UUID, member_id: UUID) -> Application | None: ...

    async def list_by_event(self, event_id: UUID, offset: int, limit: int,
                            status: ApplicationStatus | None = None) -> Sequence[Application]: ...

    async def count_by_event_and_status(self, event_id: UUID, status: ApplicationStatus) -> int: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Application]: ...

    async def create(self, dto: ApplicationCreate) -> Application: ...

    async def update(self, application_id: UUID, dto: ApplicationUpdate) -> Application: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
