from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.bracket_placement import BracketPlacement, BracketPlacementCreate, BracketPlacementUpdate


class BracketPlacementRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_bracket: bool) -> BracketPlacement | None: ...

    async def list_by_bracket(self, bracket_id: UUID) -> Sequence[BracketPlacement]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[BracketPlacement]: ...

    async def create(self, dto: BracketPlacementCreate) -> BracketPlacement: ...

    async def update(self, dto: BracketPlacementUpdate) -> BracketPlacement: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
