from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.bracket import Bracket


class BracketRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_placements: bool, load_stages: bool) -> Bracket | None: ...

    async def list_by_event(self, event_id: UUID, offset: int, limit: int) -> Sequence[Bracket]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Bracket]: ...

    async def create(self, dto: Bracket) -> Bracket: ...

    async def update(self, dto: Bracket) -> Bracket: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
