from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.drafted_player import DraftedPlayer


class DraftedPlayerRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_draft: bool, load_player: bool) -> DraftedPlayer | None: ...

    async def list_by_draft(self, draft_id: UUID) -> Sequence[DraftedPlayer]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[DraftedPlayer]: ...

    async def create(self, dto: DraftedPlayer) -> DraftedPlayer: ...

    async def update(self, dto: DraftedPlayer) -> DraftedPlayer: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
