from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.draft import Draft, DraftCreate, DraftUpdate


class DraftRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_drafted_players: bool) -> Draft | None: ...

    async def list_by_event(self, event_id: UUID, offset: int, limit: int) -> Sequence[Draft]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Draft]: ...

    async def create(self, dto: DraftCreate) -> Draft: ...

    async def update(self, dto: DraftUpdate) -> Draft: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
