from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.event import Event, EventCreate, EventUpdate


class EventRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_organizers: bool, load_integrations: bool, load_time_settings: bool,
                  load_game_roles: bool, load_custom_fields: bool, load_applications: bool, load_teams: bool,
                  load_drafts: bool, load_players: bool, load_brackets: bool) -> Event | None: ...

    async def list_public(self, offset: int, limit: int) -> Sequence[Event]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Event]: ...

    async def create(self, dto: EventCreate) -> Event: ...

    async def update(self, dto: EventUpdate) -> Event: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
