from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.event import Event, EventCreate, EventUpdate, EventStatus


class EventRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_organizers: bool = False, load_integrations: bool = False,
                  load_time_settings: bool = False, load_game_roles: bool = False,
                  load_custom_fields: bool = False, load_applications: bool = False, load_teams: bool = False,
                  load_drafts: bool = False, load_players: bool = False, load_brackets: bool = False) -> Event | None: ...

    async def list_public(self, offset: int, limit: int) -> Sequence[Event]: ...

    async def list_public_by_server(self, server_id: UUID, offset: int, limit: int) -> Sequence[Event]: ...

    async def list_by_server(self, server_id: UUID, offset: int, limit: int) -> Sequence[Event]: ...

    async def get_list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Event]: ...

    async def create(self, dto: EventCreate) -> Event: ...

    async def update(self, event_id: UUID, dto: EventUpdate) -> Event: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...

    async def transition_status(self, event_id: UUID, new_status: EventStatus) -> Event: ...
