from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.filled_application_field import FilledApplicationField, FilledApplicationFieldCreate


class FilledApplicationFieldRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_application: bool,
                  load_custom_field: bool) -> FilledApplicationField | None: ...

    async def list_by_application(self, application_id: UUID) -> Sequence[FilledApplicationField]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[FilledApplicationField]: ...

    async def create(self, dto: FilledApplicationFieldCreate) -> FilledApplicationField: ...

    async def update(self, dto: FilledApplicationFieldCreate) -> FilledApplicationField: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
