from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.match import Match, MatchCreate, MatchUpdate
from src.core.models.stage import StageFormat


class MatchRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_slots: bool = False, load_group: bool = False) -> Match | None: ...

    async def list_by_stage_group(self, group_id: UUID, offset: int, limit: int) -> Sequence[Match]: ...

    async def next_match_index(self, group_id: UUID) -> int: ...

    async def list_active_team_ids_by_event(self, event_id: UUID) -> set[UUID]: ...

    async def list_active_draft_ids_by_event(self, event_id: UUID) -> set[UUID]: ...

    async def count_incomplete_matches_by_event(self, event_id: UUID) -> int: ...

    async def get_event_context(self, match_id: UUID) -> tuple[UUID, UUID, StageFormat, UUID, UUID, UUID] | None: ...

    async def list_by_event(self, event_id: UUID, offset: int, limit: int, active: bool | None = None) -> Sequence[Match]: ...

    async def get_list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Match]: ...

    async def create(self, dto: MatchCreate) -> Match: ...

    async def update(self, match_id: UUID, dto: MatchUpdate) -> Match: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
