from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.match import Match, MatchCreate, MatchUpdate


class MatchRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_slots: bool, load_group: bool) -> Match | None: ...

    async def list_by_stage_group(self, group_id: UUID, offset: int, limit: int) -> Sequence[Match]: ...

    async def count_incomplete_matches_by_event(self, event_id: UUID) -> int: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Match]: ...

    async def create(self, dto: MatchCreate) -> Match: ...

    async def update(self, dto: MatchUpdate) -> Match: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
