from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.match_score import MatchScore, MatchScoreCreate, MatchScoreUpdate


class MatchScoreRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_slot: bool, load_team: bool) -> MatchScore | None: ...

    async def get_by_slot_id(self, slot_id: UUID, load_slot: bool, load_team: bool) -> MatchScore | None: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[MatchScore]: ...

    async def create(self, dto: MatchScoreCreate) -> MatchScore: ...

    async def update(self, score_id: UUID, dto: MatchScoreUpdate) -> MatchScore: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
