from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.match_slot import MatchSlot


class MatchSlotRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_score: bool) -> MatchSlot | None: ...

    async def list_by_match(self, match_id: UUID) -> Sequence[MatchSlot]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[MatchSlot]: ...

    async def create(self, dto: MatchSlot) -> MatchSlot: ...

    async def update(self, dto: MatchSlot) -> MatchSlot: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
