from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.organizer import Organizer


class OrganizerRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_event: bool) -> Organizer | None: ...

    async def list_by_event(self, event_id: UUID) -> Sequence[Organizer]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Organizer]: ...

    async def create(self, dto: Organizer) -> Organizer: ...

    async def update(self, dto: Organizer) -> Organizer: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
