from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.event_player import EventPlayer, EventPlayerCreate, EventPlayerUpdate, EventPlayerStatus


class PlayerRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_roles: bool = False, load_drafted: bool = False) -> EventPlayer | None: ...

    async def get_by_event_and_member(self, event_id: UUID, member_id: UUID) -> EventPlayer | None: ...

    async def list_by_event(self, event_id: UUID, offset: int, limit: int,
                            status: EventPlayerStatus | None = None) -> Sequence[EventPlayer]: ...

    async def list_by_event_with_roles(self, event_id: UUID) -> Sequence[EventPlayer]: ...

    async def get_list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[EventPlayer]: ...

    async def create(self, dto: EventPlayerCreate) -> EventPlayer: ...

    async def update(self, player_id: UUID, dto: EventPlayerUpdate) -> EventPlayer: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
