from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.player_role import PlayerRole, PlayerRoleCreate, PlayerRoleUpdate


class PlayerRoleRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_player: bool = False, load_game_role: bool = False) -> PlayerRole | None: ...

    async def list_by_player(self, player_id: UUID, offset: int, limit: int) -> Sequence[PlayerRole]: ...

    async def get_list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[PlayerRole]: ...

    async def create(self, dto: PlayerRoleCreate) -> PlayerRole: ...

    async def update(self, dto: PlayerRoleUpdate) -> PlayerRole: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
