from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.event_player import EventPlayer


class PlayerRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_roles: bool, load_drafted: bool) -> EventPlayer | None: ...

    async def get_by_event_and_member(self, event_id: UUID, member_id: UUID) -> EventPlayer | None: ...

    async def list_by_event(self, event_id: UUID, offset: int, limit: int) -> Sequence[EventPlayer]: ...

    async def list_by_event_with_roles(self, event_id: UUID) -> Sequence[EventPlayer]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[EventPlayer]: ...

    async def create(self, dto: EventPlayer) -> EventPlayer: ...

    async def update(self, dto: EventPlayer) -> EventPlayer: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
