from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.required_integration import RequiredIntegration, RequiredIntegrationCreate, RequiredIntegrationUpdate


class RequiredIntegrationRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_event: bool) -> RequiredIntegration | None: ...

    async def list_by_event(self, event_id: UUID) -> Sequence[RequiredIntegration]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[RequiredIntegration]: ...

    async def create(self, dto: RequiredIntegrationCreate) -> RequiredIntegration: ...

    async def update(self, dto: RequiredIntegrationUpdate) -> RequiredIntegration: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
