from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.selected_game_role import SelectedGameRole, SelectedGameRoleCreate, SelectedGameRoleUpdate


class SelectedGameRoleRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_player_roles: bool,
                  load_team_players: bool) -> SelectedGameRole | None: ...

    async def list_by_event(self, event_id: UUID) -> Sequence[SelectedGameRole]: ...

    async def get_list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[SelectedGameRole]: ...

    async def create(self, dto: SelectedGameRoleCreate) -> SelectedGameRole: ...

    async def update(self, dto: SelectedGameRoleUpdate) -> SelectedGameRole: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
