from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.stage_group import StageGroup


class StageGroupRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_matches: bool) -> StageGroup | None: ...

    async def list_by_stage(self, stage_id: UUID) -> Sequence[StageGroup]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[StageGroup]: ...

    async def create(self, dto: StageGroup) -> StageGroup: ...

    async def update(self, dto: StageGroup) -> StageGroup: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
