from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.stage import Stage, StageCreate, StageUpdate


class StageRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_groups: bool = False, load_settings: bool = False) -> Stage | None: ...

    async def list_by_bracket(self, bracket_id: UUID, offset: int, limit: int) -> Sequence[Stage]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Stage]: ...

    async def create(self, dto: StageCreate) -> Stage: ...

    async def update(self, dto: StageUpdate) -> Stage: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
