from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.swiss_settings import SwissSettings


class SwissSettingsRepositoryProtocol(Protocol):
    async def get_by_stage_id(self, stage_id: UUID, load_stage: bool) -> SwissSettings | None: ...

    async def delete_by_stage(self, stage_id: UUID) -> None: ...

    async def get(self, field_id: UUID) -> SwissSettings | None: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[SwissSettings]: ...

    async def create(self, dto: SwissSettings) -> SwissSettings: ...

    async def update(self, dto: SwissSettings) -> SwissSettings: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
