from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.team import Team, TeamCreate, TeamUpdate


class TeamRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_event: bool = False, load_players: bool = False) -> Team | None: ...

    async def list_by_event(self, event_id: UUID, offset: int, limit: int) -> Sequence[Team]: ...

    async def list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[Team]: ...

    async def create(self, dto: TeamCreate) -> Team: ...

    async def update(self, dto: TeamUpdate) -> Team: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
