from typing import Protocol, Any, Sequence
from uuid import UUID

from src.core.models.team_player import TeamPlayer, TeamPlayerCreate, TeamPlayerUpdate


class TeamPlayerRepositoryProtocol(Protocol):
    async def get(self, field_id: UUID, load_team: bool = False, load_role: bool = False) -> TeamPlayer | None: ...

    async def list_by_team(self, team_id: UUID) -> Sequence[TeamPlayer]: ...

    async def get_list(self, offset: int = 0, limit: int | None = 100, options: list[Any] | None = None,
                   *where_clauses: Any) -> Sequence[TeamPlayer]: ...

    async def create(self, dto: TeamPlayerCreate) -> TeamPlayer: ...

    async def update(self, dto: TeamPlayerUpdate) -> TeamPlayer: ...

    async def delete(self, field_id: UUID) -> bool: ...

    async def exists(self, field_id: UUID) -> bool: ...

    async def count(self, *where_clauses: Any) -> int: ...
